#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
. `dirname $0`/bigtop.bom

export _JAVA_OPTIONS="-Xmx2048m -XX:MaxPermSize=512m -Djava.awt.headless=true"

# Remove default stacks before we get our own stack
rm -rf ambari-server/src/main/resources/stacks/HDP*
rm -rf ambari-server/src/main/resources/stacks/BigInsights*
# Get our own stack
cp -ra ${DISTRO_DIR}/stacks/${AMBARI_STACK} ambari-server/src/main/resources/stacks/


# Build source
mvn clean install -Dstack.distribution=${AMBARI_STACK} -DskipTests -Drat.skip


# (cd contrib/management-packs/odpi-ambari-mpack ; mvn clean package -DskipTests -Drat.skip)
