#!/bin/sh -x
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

echo "-------------- Storm-do-component-build-started -----------"

base_path=`pwd`
build_support_dir=`echo ${base_path%bigtop*}`


. `dirname $0`/bigtop.bom

mvn clean install -DskipTests "$@"

cd ${base_path}
cd storm-dist/binary/
mvn package -Dgpg.passphrase=redoop123 "$@"

cd ${base_path}
cd storm-dist/source/
mvn package -Dgpg.passphrase=redoop123 "$@"

cd ${base_path}
echo "build done"

mkdir build
echo " doing untar"
for f in ${base_path}/storm-dist/binary/target/*storm*.tar.gz
do
tar -C build --strip-components=1 -xzf ${f}
done
echo "-------------- Storm-do-component-build-completed --------------"
